In [1]:
import pandas as pd

path2009 = "../Resources/2009-Annual.csv"
path2010 = "../Resources/2010-Annual.csv"
path2011 = "../Resources/2011-Annual.csv"
path2012 = "../Resources/2012-Annual.csv"
path2013 = "../Resources/2013-Annual.csv"
path2014 = "../Resources/2014-Annual.csv"
path2015 = "../Resources/2015-Annual.csv"
path2016 = "../Resources/2016-Annual.csv"
path2017 = "../Resources/2017-Annual.csv"
path2018 = "../Resources/2018-Annual.csv"
path2019 = "../Resources/2019-Annual.csv"

data2009 = pd.read_csv(path2009)
data2010 = pd.read_csv(path2010)
data2011 = pd.read_csv(path2011)
data2012 = pd.read_csv(path2012)
data2013 = pd.read_csv(path2013)
data2014 = pd.read_csv(path2014)
data2015 = pd.read_csv(path2015)
data2016 = pd.read_csv(path2016)
data2017 = pd.read_csv(path2017)
data2018 = pd.read_csv(path2018)
data2019 = pd.read_csv(path2019)

data2009

,Edition,Report Type,Measure Name,State Name,Rank,Value,Score,Lower CI,Upper CI,Source,Source Year
0,2009,2009 Annual,Air Pollution,Alabama,45.0,13.5,0.72,NaN,NaN,U.S. Environmental Protection Agency; U.S. Cen...,2006-2008
1,2009,2009 Annual,Air Pollution,Alaska,5.0,6.9,-1.92,NaN,NaN,U.S. Environmental Protection Agency; U.S. Cen...,2006-2008
2,2009,2009 Annual,Air Pollution,Arizona,22.0,10.5,-0.48,NaN,NaN,U.S. Environmental Protection Agency; U.S. Cen...,2006-2008
3,2009,2009 Annual,Air Pollution,Arkansas,32.0,11.8,0.04,NaN,NaN,U.S. Environmental Protection Agency; U.S. Cen...,2006-2008
4,2009,2009 Annual,Air Pollution,California,47.0,13.9,0.88,NaN,NaN,U.S. Environmental Protection Agency; U.S. Cen...,2006-2008
...,...,...,...,...,...,...,...,...,...,...,...
12890,2009,2009 Annual,Voter Registration,Vermont,25.0,72.5,0.31,75.5,69.5,AHR data,NaN
12891,2009,2009 Annual,Voter Registration,Washington,27.0,71.7,0.15,74.0,69.4,AHR data,NaN
12892,2009,2009 Annual,Voter Registration,Wisconsin,8.0,76.4,1.13,78.8,74.0,AHR data,NaN
12893,2009,2009 Annual,Voter Registration,West Virginia,45.0,66.1,-1.03,68.8,63.4,AHR data,NaN
12894,2009,2009 Annual,Voter Registration,Wyoming,37.0,69.3,-0.36,72.3,66.3,AHR data,NaN

In [2]:
data2016['Measure Name'].unique()

array(['Air Pollution', 'All Determinants', 'All Outcomes', 'Arthritis',
       'Arthritis - $25-$49,999', 'Arthritis - $50-$74,999',
       'Arthritis - $75,000 or More', 'Arthritis - Ages 18-44',
       'Arthritis - Ages 45-64', 'Arthritis - Ages 65+',
       'Arthritis - American Indian/Alaska Native', 'Arthritis - Asian',
       'Arthritis - Black', 'Arthritis - College Grad',
       'Arthritis - Female', 'Arthritis - Hawaiian/Pacific Islander',
       'Arthritis - High School Grad', 'Arthritis - Hispanic',
       'Arthritis - Less Than $25,000',
       'Arthritis - Less Than High School', 'Arthritis - Male',
       'Arthritis - Multiracial', 'Arthritis - Other Race',
       'Arthritis - Some College', 'Arthritis - White', 'Asthma',
       'Asthma - $25-$49,999', 'Asthma - $50-$74,999',
       'Asthma - $75,000 or More', 'Asthma - Ages 18-44',
       'Asthma - Ages 45-64', 'Asthma - Ages 65+',
       'Asthma - American Indian/Alaska Native', 'Asthma - Asian',
       'Asthma - Black', 'Asthma - College Grad', 'Asthma - Female',
       'Asthma - Hawaiian/Pacific Islander', 'Asthma - High School Grad',
       'Asthma - Hispanic', 'Asthma - Less Than $25,000',
       'Asthma - Less Than High School', 'Asthma - Male',
       'Asthma - Multiracial', 'Asthma - Other Race',
       'Asthma - Some College', 'Asthma - White',
       'Avoided Care Due to Cost',
       'Avoided Care Due to Cost - American Indian/Alaska Native',
       'Avoided Care Due to Cost - Asian',
       'Avoided Care Due to Cost - Black',
       'Avoided Care Due to Cost - Hawaiian/Pacific Islander',
       'Avoided Care Due to Cost - Hispanic',
       'Avoided Care Due to Cost - Multiracial',
       'Avoided Care Due to Cost - Other Race',
       'Avoided Care Due to Cost - White', 'Behaviors', 'Binge Drinking',
       'Binge Drinking - $25-$49,999', 'Binge Drinking - $50-$74,999',
       'Binge Drinking - $75,000 or More', 'Binge Drinking - Ages 18-44',
       'Binge Drinking - Ages 45-64', 'Binge Drinking - Ages 65+',
       'Binge Drinking - American Indian/Alaska Native',
       'Binge Drinking - Asian', 'Binge Drinking - Black',
       'Binge Drinking - College Grad', 'Binge Drinking - Female',
       'Binge Drinking - Hawaiian/Pacific Islander',
       'Binge Drinking - High School Grad', 'Binge Drinking - Hispanic',
       'Binge Drinking - Less Than $25,000',
       'Binge Drinking - Less Than High School', 'Binge Drinking - Male',
       'Binge Drinking - Rural', 'Binge Drinking - Some College',
       'Binge Drinking - Suburban', 'Binge Drinking - Urban',
       'Binge Drinking - White', 'Cancer', 'Cancer - $25-$49,999',
       'Cancer - $50-$74,999', 'Cancer - $75,000 or More',
       'Cancer - Ages 18-44', 'Cancer - Ages 45-64', 'Cancer - Ages 65+',
       'Cancer - American Indian/Alaska Native', 'Cancer - Asian',
       'Cancer - Black', 'Cancer - College Grad', 'Cancer - Female',
       'Cancer - Hawaiian/Pacific Islander', 'Cancer - High School Grad',
       'Cancer - Hispanic', 'Cancer - Less Than $25,000',
       'Cancer - Less Than High School', 'Cancer - Male',
       'Cancer - Multiracial', 'Cancer - Other Race',
       'Cancer - Some College', 'Cancer - White', 'Cancer Deaths',
       'Cancer Deaths - American Indian/Alaska Native',
       'Cancer Deaths - Asian/Pacific Islander',
       'Cancer Deaths - Black/African American',
       'Cancer Deaths - Crude Rate', 'Cancer Deaths - Female',
       'Cancer Deaths - Hispanic/Latino', 'Cancer Deaths - Male',
       'Cancer Deaths - Standard Age Adjustment', 'Cancer Deaths - White',
       'Cardiovascular Deaths',
       'Cardiovascular Deaths - American Indian/Alaska Native',
       'Cardiovascular Deaths - Asian/Pacific Islander',
       'Cardiovascular Deaths - Black/African American',
       'Cardiovascular Deaths - Crude Rate',
       'Cardiovascular Deaths - Female',
       'Cardiovascular Deaths - Hispanic/Latino',
       'Cardiovascular Deaths - Male',
       'Cardiovascular Deaths - Standard Age Adjustment',
       'Cardiovascular Deaths - White', 'Cardiovascular Diseases',
       'Cardiovascular Diseases - $25-$49,999',
       'Cardiovascular Diseases - $50-$74,999',
       'Cardiovascular Diseases - $75,000 or More',
       'Cardiovascular Diseases - Ages 18-44',
       'Cardiovascular Diseases - Ages 45-64',
       'Cardiovascular Diseases - Ages 65+',
       'Cardiovascular Diseases - American Indian/Alaska Native',
       'Cardiovascular Diseases - Asian',
       'Cardiovascular Diseases - Black',
       'Cardiovascular Diseases - College Grad',
       'Cardiovascular Diseases - Female',
       'Cardiovascular Diseases - Hawaiian/Pacific Islander',
       'Cardiovascular Diseases - High School Grad',
       'Cardiovascular Diseases - Hispanic',
       'Cardiovascular Diseases - Less Than $25,000',
       'Cardiovascular Diseases - Less Than High School',
       'Cardiovascular Diseases - Male',
       'Cardiovascular Diseases - Multiracial',
       'Cardiovascular Diseases - Other Race',
       'Cardiovascular Diseases - Some College',
       'Cardiovascular Diseases - White', 'Children in Poverty',
       'Children in Poverty - American Indian or Alaska Native',
       'Children in Poverty - Asian', 'Children in Poverty - Black',
       'Children in Poverty - Hawaiian/Pacific Islander',
       'Children in Poverty - Hispanic',
       'Children in Poverty - Multiracial', 'Children in Poverty - White',
       'Chlamydia', 'Chlamydia - American Indian/Alaska Native',
       'Chlamydia - Asian', 'Chlamydia - Black/African American',
       'Chlamydia - Female', 'Chlamydia - Hispanic/Latino',
       'Chlamydia - Male', 'Chlamydia - White', 'Cholesterol Check',
       'Cholesterol Check - $25-$49,999',
       'Cholesterol Check - $50-$74,999',
       'Cholesterol Check - $75,000 or More',
       'Cholesterol Check - Ages 18-44', 'Cholesterol Check - Ages 45-64',
       'Cholesterol Check - Ages 65+',
       'Cholesterol Check - American Indian/Alaska Native',
       'Cholesterol Check - Asian', 'Cholesterol Check - Black',
       'Cholesterol Check - College Grad', 'Cholesterol Check - Female',
       'Cholesterol Check - Hawaiian/Pacific Islander',
       'Cholesterol Check - High School Grad',
       'Cholesterol Check - Hispanic',
       'Cholesterol Check - Less Than $25,000',
       'Cholesterol Check - Less Than High School',
       'Cholesterol Check - Male', 'Cholesterol Check - Rural',
       'Cholesterol Check - Some College', 'Cholesterol Check - Suburban',
       'Cholesterol Check - Urban', 'Cholesterol Check - White',
       'Chronic Drinking', 'Chronic Drinking - $25-$49,999',
       'Chronic Drinking - $50-$74,999',
       'Chronic Drinking - $75,000 or More',
       'Chronic Drinking - Ages 18-44', 'Chronic Drinking - Ages 45-64',
       'Chronic Drinking - Ages 65+',
       'Chronic Drinking - American Indian/Alaska Native',
       'Chronic Drinking - Asian', 'Chronic Drinking - Black',
       'Chronic Drinking - College Grad', 'Chronic Drinking - Female',
       'Chronic Drinking - Hawaiian/Pacific Islander',
       'Chronic Drinking - High School Grad',
       'Chronic Drinking - Hispanic',
       'Chronic Drinking - Less Than $25,000',
       'Chronic Drinking - Less Than High School',
       'Chronic Drinking - Male', 'Chronic Drinking - Rural',
       'Chronic Drinking - Some College', 'Chronic Drinking - Suburban',
       'Chronic Drinking - Urban', 'Chronic Drinking - White',
       'Chronic Kidney Disease', 'Chronic Kidney Disease - $25-$49,999',
       'Chronic Kidney Disease - $50-$74,999',
       'Chronic Kidney Disease - $75,000 or More',
       'Chronic Kidney Disease - Ages 18-44',
       'Chronic Kidney Disease - Ages 45-64',
       'Chronic Kidney Disease - Ages 65+',
       'Chronic Kidney Disease - American Indian/Alaska Native',
       'Chronic Kidney Disease - Asian', 'Chronic Kidney Disease - Black',
       'Chronic Kidney Disease - College Grad',
       'Chronic Kidney Disease - Female',
       'Chronic Kidney Disease - Hawaiian/Pacific Islander',
       'Chronic Kidney Disease - High School Grad',
       'Chronic Kidney Disease - Hispanic',
       'Chronic Kidney Disease - Less Than $25,000',
       'Chronic Kidney Disease - Less Than High School',
       'Chronic Kidney Disease - Male',
       'Chronic Kidney Disease - Multiracial',
       'Chronic Kidney Disease - Other Race',
       'Chronic Kidney Disease - Some College',
       'Chronic Kidney Disease - White',
       'Chronic Obstructive Pulmonary Disease',
       'Chronic Obstructive Pulmonary Disease - $25-$49,999',
       'Chronic Obstructive Pulmonary Disease - $50-$74,999',
       'Chronic Obstructive Pulmonary Disease - $75,000 or More',
       'Chronic Obstructive Pulmonary Disease - Ages 18-44',
       'Chronic Obstructive Pulmonary Disease - Ages 45-64',
       'Chronic Obstructive Pulmonary Disease - Ages 65+',
       'Chronic Obstructive Pulmonary Disease - American Indian/Alaska Native',
       'Chronic Obstructive Pulmonary Disease - Asian',
       'Chronic Obstructive Pulmonary Disease - Black',
       'Chronic Obstructive Pulmonary Disease - College Grad',
       'Chronic Obstructive Pulmonary Disease - Female',
       'Chronic Obstructive Pulmonary Disease - Hawaiian/Pacific Islander',
       'Chronic Obstructive Pulmonary Disease - High School Grad',
       'Chronic Obstructive Pulmonary Disease - Hispanic',
       'Chronic Obstructive Pulmonary Disease - Less Than $25,000',
       'Chronic Obstructive Pulmonary Disease - Less Than High School',
       'Chronic Obstructive Pulmonary Disease - Male',
       'Chronic Obstructive Pulmonary Disease - Multiracial',
       'Chronic Obstructive Pulmonary Disease - Other Race',
       'Chronic Obstructive Pulmonary Disease - Some College',
       'Chronic Obstructive Pulmonary Disease - White', 'Clinical Care',
       'Colorectal Cancer Screening',
       'Colorectal Cancer Screening - $25-$49,999',
       'Colorectal Cancer Screening - $50-$74,999',
       'Colorectal Cancer Screening - $75,000 or More',
       'Colorectal Cancer Screening - American Indian/Alaska Native',
       'Colorectal Cancer Screening - Asian',
       'Colorectal Cancer Screening - Black',
       'Colorectal Cancer Screening - College Grad',
       'Colorectal Cancer Screening - Female',
       'Colorectal Cancer Screening - Hawaiian/Pacific Islander',
       'Colorectal Cancer Screening - High School Grad',
       'Colorectal Cancer Screening - Hispanic',
       'Colorectal Cancer Screening - Less Than $25,000',
       'Colorectal Cancer Screening - Less Than High School',
       'Colorectal Cancer Screening - Male',
       'Colorectal Cancer Screening - Rural',
       'Colorectal Cancer Screening - Some College',
       'Colorectal Cancer Screening - Suburban',
       'Colorectal Cancer Screening - Urban',
       'Colorectal Cancer Screening - White', 'Community & Environment',
       'Dedicated HC Provider - $25-$49,999',
       'Dedicated HC Provider - $50-$74,999',
       'Dedicated HC Provider - $75,000 or More',
       'Dedicated HC Provider - 18-44', 'Dedicated HC Provider - 45-64',
       'Dedicated HC Provider - 65+',
       'Dedicated HC Provider - American Indian/Alaska Native',
       'Dedicated HC Provider - Asian', 'Dedicated HC Provider - Black',
       'Dedicated HC Provider - College Grad',
       'Dedicated HC Provider - Female',
       'Dedicated HC Provider - Hawaiian/Pacific Islander',
       'Dedicated HC Provider - High School Grad',
       'Dedicated HC Provider - Hispanic',
       'Dedicated HC Provider - Less Than $25,000',
       'Dedicated HC Provider - Less Than High School',
       'Dedicated HC Provider - Male', 'Dedicated HC Provider - Rural',
       'Dedicated HC Provider - Some College',
       'Dedicated HC Provider - Suburban',
       'Dedicated HC Provider - Urban', 'Dedicated HC Provider - White',
       'Dedicated Health Care Provider', 'Dental Visit',
       'Dental Visit - $25-$49,999', 'Dental Visit - $50-$74,999',
       'Dental Visit - $75,000 or More', 'Dental Visit - Ages 18-44',
       'Dental Visit - Ages 45-64', 'Dental Visit - Ages 65+',
       'Dental Visit - American Indian/Alaska Native',
       'Dental Visit - Asian', 'Dental Visit - Black',
       'Dental Visit - College Grad', 'Dental Visit - Female',
       'Dental Visit - Hawaiian/Pacific Islander',
       'Dental Visit - High School Grad', 'Dental Visit - Hispanic',
       'Dental Visit - Less Than $25,000',
       'Dental Visit - Less Than High School', 'Dental Visit - Male',
       'Dental Visit - Rural', 'Dental Visit - Some College',
       'Dental Visit - Suburban', 'Dental Visit - Urban',
       'Dental Visit - White', 'Dentists', 'Depression',
       'Depression - $25-$49,999', 'Depression - $50-$74,999',
       'Depression - $75,000 or More', 'Depression - Ages 18-44',
       'Depression - Ages 45-64', 'Depression - Ages 65+',
       'Depression - American Indian/Alaska Native', 'Depression - Asian',
       'Depression - Black', 'Depression - College Grad',
       'Depression - Female', 'Depression - Hawaiian/Pacific Islander',
       'Depression - High School Grad', 'Depression - Hispanic',
       'Depression - Less Than $25,000',
       'Depression - Less Than High School', 'Depression - Male',
       'Depression - Multiracial', 'Depression - Other Race',
       'Depression - Some College', 'Depression - White', 'Diabetes',
       'Diabetes - $25-$49,999', 'Diabetes - $50-$74,999',
       'Diabetes - $75,000 or More', 'Diabetes - Ages 18-44',
       'Diabetes - Ages 45-64', 'Diabetes - Ages 65+',
       'Diabetes - American Indian/Alaska Native', 'Diabetes - Asian',
       'Diabetes - Black', 'Diabetes - College Grad', 'Diabetes - Female',
       'Diabetes - Hawaiian/Pacific Islander',
       'Diabetes - High School Grad', 'Diabetes - Hispanic',
       'Diabetes - Less Than $25,000', 'Diabetes - Less Than High School',
       'Diabetes - Male', 'Diabetes - Multiracial',
       'Diabetes - Other Race', 'Diabetes - Rural',
       'Diabetes - Some College', 'Diabetes - Suburban',
       'Diabetes - Urban', 'Diabetes - White',
       'Disparity in Health Status', 'Drug Deaths',
       'Drug Deaths - American Indian/Alaska Native',
       'Drug Deaths - Asian/Pacific Islander',
       'Drug Deaths - Black/African American', 'Drug Deaths - Female',
       'Drug Deaths - Hispanic/Latino', 'Drug Deaths - Male',
       'Drug Deaths - White', 'Drug Deaths (1-year)',
       'Drug Deaths (1-year) - Ages 15-24',
       'Drug Deaths (1-year) - Ages 25-34',
       'Drug Deaths (1-year) - Ages 35-44',
       'Drug Deaths (1-year) - Ages 45-54',
       'Drug Deaths (1-year) - Ages 55-64',
       'Drug Deaths (1-year) - Ages 65-74',
       'Drug Deaths (1-year) - American Indian/Alaska Native',
       'Drug Deaths (1-year) - Asian/Pacific Islander',
       'Drug Deaths (1-year) - Black/African American',
       'Drug Deaths (1-year) - Female', 'Drug Deaths (1-year) - Hispanic',
       'Drug Deaths (1-year) - Male', 'Drug Deaths (1-year) - White',
       'Excessive Drinking', 'Excessive Drinking - $25-$49,999',
       'Excessive Drinking - $50-$74,999',
       'Excessive Drinking - $75,000 or More',
       'Excessive Drinking - Ages 18-44',
       'Excessive Drinking - Ages 45-64', 'Excessive Drinking - Ages 65+',
       'Excessive Drinking - American Indian/Alaska Native',
       'Excessive Drinking - Asian', 'Excessive Drinking - Black',
       'Excessive Drinking - College Grad', 'Excessive Drinking - Female',
       'Excessive Drinking - Hawaiian/Pacific Islander',
       'Excessive Drinking - High School Grad',
       'Excessive Drinking - Hispanic',
       'Excessive Drinking - Less Than $25,000',
       'Excessive Drinking - Less Than High School',
       'Excessive Drinking - Male', 'Excessive Drinking - Rural',
       'Excessive Drinking - Some College',
       'Excessive Drinking - Suburban', 'Excessive Drinking - Urban',
       'Excessive Drinking - White', 'Excessive Drinking Rate of Change',
       'Excessive Drinking Rate of Change-College Graduate',
       'Excessive Drinking Rate of Change-High School Grad',
       'Excessive Drinking Rate of Change-Less Than High S',
       'Excessive Drinking Rate of Change-Some College', 'Exercise',
       'Exercise - $25-$49,999', 'Exercise - $50-$74,999',
       'Exercise - $75,000 or More', 'Exercise - Ages 18-44',
       'Exercise - Ages 45-64', 'Exercise - Ages 65+',
       'Exercise - American Indian/Alaska Native', 'Exercise - Asian',
       'Exercise - Black', 'Exercise - College Grad', 'Exercise - Female',
       'Exercise - Hawaiian/Pacific Islander',
       'Exercise - High School Grad', 'Exercise - Hispanic',
       'Exercise - Less Than $25,000', 'Exercise - Less Than High School',
       'Exercise - Male', 'Exercise - Multiracial',
       'Exercise - Other Race', 'Exercise - Some College',
       'Exercise - White', 'Flu Vaccination',
       'Flu Vaccination - $25-$49,999', 'Flu Vaccination - $50-$74,999',
       'Flu Vaccination - $75,000 or More', 'Flu Vaccination - 18-44',
       'Flu Vaccination - 45-64', 'Flu Vaccination - 65+',
       'Flu Vaccination - American Indian', 'Flu Vaccination - Asian',
       'Flu Vaccination - Black', 'Flu Vaccination - College Grad',
       'Flu Vaccination - Female', 'Flu Vaccination - Hawaiian PI',
       'Flu Vaccination - High School Grad', 'Flu Vaccination - Hispanic',
       'Flu Vaccination - Less Than $25,000',
       'Flu Vaccination - Less Than HS', 'Flu Vaccination - Male',
       'Flu Vaccination - Multiracial', 'Flu Vaccination - Other Race',
       'Flu Vaccination - Some College', 'Flu Vaccination - White',
       'Food Insecurity', 'Frequent Mental Distress',
       'Frequent Mental Distress - $25-$49,999',
       'Frequent Mental Distress - $50-$74,999',
       'Frequent Mental Distress - $75,000 or More',
       'Frequent Mental Distress - Ages 18-44',
       'Frequent Mental Distress - Ages 45-64',
       'Frequent Mental Distress - Ages 65+',
       'Frequent Mental Distress - American Indian/Alaska Native',
       'Frequent Mental Distress - Asian',
       'Frequent Mental Distress - Black',
       'Frequent Mental Distress - College Grad',
       'Frequent Mental Distress - Female',
       'Frequent Mental Distress - Hawaiian/Pacific Islander',
       'Frequent Mental Distress - High School Grad',
       'Frequent Mental Distress - Hispanic',
       'Frequent Mental Distress - Less Than $25,000',
       'Frequent Mental Distress - Less Than High School',
       'Frequent Mental Distress - Male',
       'Frequent Mental Distress - Rural',
       'Frequent Mental Distress - Some College',
       'Frequent Mental Distress - Suburban',
       'Frequent Mental Distress - Urban',
       'Frequent Mental Distress - White', 'Frequent Physical Distress',
       'Frequent Physical Distress - $25-$49,999',
       'Frequent Physical Distress - $50-$74,999',
       'Frequent Physical Distress - $75,000 or More',
       'Frequent Physical Distress - Ages 18-44',
       'Frequent Physical Distress - Ages 45-64',
       'Frequent Physical Distress - Ages 65+',
       'Frequent Physical Distress - American Indian/Alaska Native',
       'Frequent Physical Distress - Asian',
       'Frequent Physical Distress - Black',
       'Frequent Physical Distress - College Grad',
       'Frequent Physical Distress - Female',
       'Frequent Physical Distress - Hawaiian/Pacific Islander',
       'Frequent Physical Distress - High School Grad',
       'Frequent Physical Distress - Hispanic',
       'Frequent Physical Distress - Less Than $25,000',
       'Frequent Physical Distress - Less Than High School',
       'Frequent Physical Distress - Male',
       'Frequent Physical Distress - Rural',
       'Frequent Physical Distress - Some College',
       'Frequent Physical Distress - Suburban',
       'Frequent Physical Distress - Urban',

In [3]:
clean2009 = data2009.loc[(data2009['Measure Name'] == 'Overall') | (data2009['Measure Name'] == 'All Determinants') | (data2009['Measure Name'] == 'Primary Care Physicians') | (data2009['Measure Name'] == 'Health Status - Female')]
clean2009 = clean2009.replace(to_replace='Health Status - Female', value='High Health Status - Female')
clean2009 = clean2009[['Edition','Measure Name','State Name','Rank','Value']]
clean2009 = clean2009.rename(columns={'Edition':'Year'})
clean2009.reset_index(drop=True,inplace=True)
clean2009

     Year             Measure Name            State Name  Rank    Value
0    2009         All Determinants                Alaska  34.0   -0.121
1    2009         All Determinants               Arizona  27.0   -0.037
2    2009         All Determinants              Arkansas  41.0   -0.264
3    2009         All Determinants            California  24.0    0.134
4    2009         All Determinants               Alabama  43.0   -0.306
..    ...                      ...                   ...   ...      ...
203  2009  Primary Care Physicians         West Virginia  34.0  104.700
204  2009  Primary Care Physicians             Wisconsin  19.0  120.000
205  2009  Primary Care Physicians               Wyoming  44.0   89.600
206  2009  Primary Care Physicians         United States   NaN  120.600
207  2009  Primary Care Physicians  District of Columbia   NaN  320.000

[208 rows x 5 columns]

In [4]:
clean2010 = data2010.loc[(data2010['Measure Name'] == 'Overall') | (data2010['Measure Name'] == 'All Determinants') | (data2010['Measure Name'] == 'Primary Care Physicians') | (data2010['Measure Name'] == 'Health Status - Female')]
clean2010 = clean2010.replace(to_replace='Health Status - Female', value='High Health Status - Female')
clean2010 = clean2010[['Edition','Measure Name','State Name','Rank','Value']]
clean2010 = clean2010.rename(columns={'Edition':'Year'})
clean2010.reset_index(drop=True,inplace=True)
clean2010

     Year             Measure Name            State Name  Rank    Value
0    2010         All Determinants            New Mexico  34.0   -0.108
1    2010         All Determinants              New York  26.0    0.042
2    2010         All Determinants        North Carolina  35.0   -0.123
3    2010         All Determinants          North Dakota  11.0    0.365
4    2010         All Determinants                  Ohio  30.0   -0.039
..    ...                      ...                   ...   ...      ...
203  2010  Primary Care Physicians         West Virginia  33.0  105.400
204  2010  Primary Care Physicians             Wisconsin  19.0  120.600
205  2010  Primary Care Physicians               Wyoming  43.0   92.700
206  2010  Primary Care Physicians         United States   NaN  120.500
207  2010  Primary Care Physicians  District of Columbia   NaN  328.100

[208 rows x 5 columns]

In [5]:
clean2011 = data2011.loc[(data2011['Measure Name'] == 'Overall') | (data2011['Measure Name'] == 'All Determinants') | (data2011['Measure Name'] == 'Primary Care Physicians') | (data2011['Measure Name'] == 'Health Status - Female')]
clean2011 = clean2011.replace(to_replace='Health Status - Female', value='High Health Status - Female')
clean2011 = clean2011[['Edition','Measure Name','State Name','Rank','Value']]
clean2011 = clean2011.rename(columns={'Edition':'Year'})
clean2011.reset_index(drop=True,inplace=True)
clean2011

     Year             Measure Name     State Name  Rank    Value
0    2011         All Determinants          Texas  49.0   -0.539
1    2011         All Determinants           Ohio  36.0   -0.190
2    2011         All Determinants        Vermont   1.0    0.904
3    2011         All Determinants  New Hampshire   3.0    0.723
4    2011         All Determinants   Rhode Island   9.0    0.397
..    ...                      ...            ...   ...      ...
203  2011  Primary Care Physicians        Arizona  44.0   92.600
204  2011  Primary Care Physicians        Indiana  36.0  102.500
205  2011  Primary Care Physicians     California  22.0  119.000
206  2011  Primary Care Physicians       Arkansas  41.0   99.500
207  2011  Primary Care Physicians           Iowa  47.0   84.200

[208 rows x 5 columns]

In [6]:
clean2012 = data2012.loc[(data2012['Measure Name'] == 'Overall') | (data2012['Measure Name'] == 'All Determinants') | (data2012['Measure Name'] == 'Primary Care Physicians') | (data2012['Measure Name'] == 'High Health Status - Female')]
clean2012 = clean2012[['Edition','Measure Name','State Name','Rank','Value']]
clean2012 = clean2012.rename(columns={'Edition':'Year'})
clean2012.reset_index(drop=True,inplace=True)
clean2012

     Year             Measure Name            State Name  Rank    Value
0    2012         All Determinants                Alaska  26.0    0.068
1    2012         All Determinants               Alabama  44.0   -0.389
2    2012         All Determinants         United States   NaN      NaN
3    2012         All Determinants              Arkansas  48.0   -0.586
4    2012         All Determinants               Arizona  29.0    0.006
..    ...                      ...                   ...   ...      ...
203  2012  Primary Care Physicians         West Virginia  34.0  102.500
204  2012  Primary Care Physicians             Wisconsin  18.0  121.300
205  2012  Primary Care Physicians               Wyoming  44.0   89.600
206  2012  Primary Care Physicians         United States   NaN  119.900
207  2012  Primary Care Physicians  District of Columbia   NaN  342.900

[208 rows x 5 columns]

In [7]:
clean2013 = data2013.loc[(data2013['Measure Name'] == 'Overall') | (data2013['Measure Name'] == 'All Determinants') | (data2013['Measure Name'] == 'Primary Care Physicians') | (data2013['Measure Name'] == 'High Health Status - Female')]
clean2013 = clean2013[['Edition','Measure Name','State Name','Rank','Value']]
clean2013 = clean2013.rename(columns={'Edition':'Year'})
clean2013.reset_index(drop=True,inplace=True)
clean2013

     Year             Measure Name            State Name  Rank    Value
0    2013         All Determinants                Alaska  26.0    0.053
1    2013         All Determinants               Alabama  46.0   -0.449
2    2013         All Determinants         United States   NaN      NaN
3    2013         All Determinants              Arkansas  50.0   -0.627
4    2013         All Determinants               Arizona  29.0    0.002
..    ...                      ...                   ...   ...      ...
203  2013  Primary Care Physicians         West Virginia  34.0  105.500
204  2013  Primary Care Physicians             Wisconsin  19.0  121.800
205  2013  Primary Care Physicians               Wyoming  44.0   90.200
206  2013  Primary Care Physicians         United States   NaN  120.900
207  2013  Primary Care Physicians  District of Columbia   NaN  326.700

[208 rows x 5 columns]

In [8]:
clean2014 = data2014.loc[(data2014['Measure Name'] == 'Overall') | (data2014['Measure Name'] == 'All Determinants') | (data2014['Measure Name'] == 'Primary Care Physicians') | (data2014['Measure Name'] == 'High Health Status - Female')]
clean2014 = clean2014[['Edition','Measure Name','State Name','Rank','Value']]
clean2014 = clean2014.rename(columns={'Edition':'Year'})
clean2014.reset_index(drop=True,inplace=True)
clean2014

     Year             Measure Name            State Name Rank    Value
0    2014         All Determinants                Alaska   29   -0.058
1    2014         All Determinants               Alabama   41   -0.335
2    2014         All Determinants         United States  NaN      NaN
3    2014         All Determinants              Arkansas   49   -0.655
4    2014         All Determinants               Arizona   28   -0.008
..    ...                      ...                   ...  ...      ...
203  2014  Primary Care Physicians         West Virginia   34  107.800
204  2014  Primary Care Physicians             Wisconsin   17  125.000
205  2014  Primary Care Physicians               Wyoming   45   90.000
206  2014  Primary Care Physicians         United States  NaN  123.500
207  2014  Primary Care Physicians  District of Columbia  NaN  324.600

[208 rows x 5 columns]

In [9]:
clean2015 = data2015.loc[(data2015['Measure Name'] == 'Overall') | (data2015['Measure Name'] == 'All Determinants') | (data2015['Measure Name'] == 'Primary Care Physicians') | (data2015['Measure Name'] == 'High Health Status - Female')]
clean2015 = clean2015[['Edition','Measure Name','State Name','Rank','Value']]
clean2015 = clean2015.rename(columns={'Edition':'Year'})
clean2015.reset_index(drop=True,inplace=True)
clean2015

     Year             Measure Name            State Name  Rank    Value
0    2015         All Determinants                Alaska  30.0   -0.114
1    2015         All Determinants               Alabama  43.0   -0.371
2    2015         All Determinants         United States   NaN      NaN
3    2015         All Determinants              Arkansas  48.0   -0.584
4    2015         All Determinants               Arizona  32.0   -0.141
..    ...                      ...                   ...   ...      ...
203  2015  Primary Care Physicians         West Virginia  33.0  109.200
204  2015  Primary Care Physicians             Wisconsin  19.0  125.300
205  2015  Primary Care Physicians               Wyoming  46.0   88.700
206  2015  Primary Care Physicians         United States   NaN  127.400
207  2015  Primary Care Physicians  District of Columbia   NaN  325.500

[208 rows x 5 columns]

In [10]:
clean2016 = data2016.loc[(data2016['Measure Name'] == 'Overall') | (data2016['Measure Name'] == 'All Determinants') | (data2016['Measure Name'] == 'Primary Care Physicians') | (data2016['Measure Name'] == 'High Health Status - Female')]
clean2016 = clean2016[['Edition','Measure Name','State Name','Rank','Value']]
clean2016 = clean2016.rename(columns={'Edition':'Year'})
clean2016.reset_index(drop=True,inplace=True)
clean2016

     Year             Measure Name            State Name  Rank    Value
0    2016         All Determinants                Alaska  33.0   -0.139
1    2016         All Determinants               Alabama  46.0   -0.427
2    2016         All Determinants              Arkansas  48.0   -0.506
3    2016         All Determinants               Arizona  30.0   -0.062
4    2016         All Determinants            California  16.0    0.277
..    ...                      ...                   ...   ...      ...
199  2016  Primary Care Physicians             Wisconsin  21.0  140.300
200  2016  Primary Care Physicians         West Virginia  18.0  151.200
201  2016  Primary Care Physicians               Wyoming  47.0  103.700
202  2016  Primary Care Physicians         United States   NaN  145.300
203  2016  Primary Care Physicians  District of Columbia   NaN  431.600

[204 rows x 5 columns]

In [11]:
clean2017 = data2017.loc[(data2017['Measure Name'] == 'Overall') | (data2017['Measure Name'] == 'All Determinants') | (data2017['Measure Name'] == 'Primary Care Physicians') | (data2017['Measure Name'] == 'High Health Status - Female')]
clean2017 = clean2017[['Edition','Measure Name','State Name','Rank','Value']]
clean2017 = clean2017.rename(columns={'Edition':'Year'})
clean2017.reset_index(drop=True,inplace=True)
clean2017

     Year             Measure Name            State Name  Rank    Value
0    2017         All Determinants                Alaska  34.0   -0.190
1    2017         All Determinants               Alabama  47.0   -0.427
2    2017         All Determinants              Arkansas  48.0   -0.449
3    2017         All Determinants               Arizona  33.0   -0.157
4    2017         All Determinants            California  18.0    0.245
..    ...                      ...                   ...   ...      ...
199  2017  Primary Care Physicians             Wisconsin  20.0  145.200
200  2017  Primary Care Physicians         West Virginia  17.0  159.600
201  2017  Primary Care Physicians               Wyoming  48.0  105.700
202  2017  Primary Care Physicians         United States   NaN  149.700
203  2017  Primary Care Physicians  District of Columbia   NaN  451.100

[204 rows x 5 columns]

In [12]:
clean2018 = data2018.loc[(data2018['Measure Name'] == 'Overall') | (data2018['Measure Name'] == 'All Determinants') | (data2018['Measure Name'] == 'Primary Care Physicians') | (data2018['Measure Name'] == 'High Health Status - Female')]
clean2018 = clean2018[['Edition','Measure Name','State Name','Rank','Value']]
clean2018 = clean2018.rename(columns={'Edition':'Year'})
clean2018.reset_index(drop=True,inplace=True)
clean2018

     Year             Measure Name     State Name  Rank    Value
0    2018         All Determinants         Alaska  35.0   -0.227
1    2018         All Determinants        Alabama  48.0   -0.483
2    2018         All Determinants       Arkansas  45.0   -0.361
3    2018         All Determinants        Arizona  33.0   -0.168
4    2018         All Determinants     California  15.0    0.312
..    ...                      ...            ...   ...      ...
199  2018  Primary Care Physicians        Vermont  11.0  183.300
200  2018  Primary Care Physicians     Washington  23.0  146.500
201  2018  Primary Care Physicians      Wisconsin  20.0  150.100
202  2018  Primary Care Physicians  West Virginia  14.0  168.500
203  2018  Primary Care Physicians        Wyoming  46.0  109.400

[204 rows x 5 columns]

In [13]:
clean2019 = data2019.loc[(data2019['Measure Name'] == 'Overall') | (data2019['Measure Name'] == 'All Determinants') | (data2019['Measure Name'] == 'Primary Care Physicians') | (data2019['Measure Name'] == 'High Health Status - Female')]
clean2019 = clean2019[['Edition','Measure Name','State Name','Rank','Value']]
clean2019 = clean2019.rename(columns={'Edition':'Year'})
clean2019.reset_index(drop=True,inplace=True)
clean2019

     Year             Measure Name     State Name  Rank    Value
0    2019         All Determinants         Alaska  29.0   -0.027
1    2019         All Determinants        Alabama  46.0   -0.437
2    2019         All Determinants       Arkansas  48.0   -0.478
3    2019         All Determinants        Arizona  34.0   -0.187
4    2019         All Determinants     California  16.0    0.272
..    ...                      ...            ...   ...      ...
201  2019  Primary Care Physicians        Vermont  11.0  188.700
202  2019  Primary Care Physicians     Washington  23.0  150.000
203  2019  Primary Care Physicians      Wisconsin  21.0  152.400
204  2019  Primary Care Physicians  West Virginia  14.0  172.800
205  2019  Primary Care Physicians        Wyoming  46.0  111.000

[206 rows x 5 columns]

In [14]:
cleanRankings = pd.concat([clean2009, clean2010, clean2011, clean2012, clean2013, clean2014, clean2015, clean2016, clean2017, clean2018, clean2019])
cleanRankings.reset_index(drop=True,inplace=True)
cleanRankings = cleanRankings.rename(columns={'Year':'year','Measure Name':'measure_name','State Name':'state','Rank':'rank','Value':'value'})
cleanRankings

      year             measure_name          state rank    value
0     2009         All Determinants         Alaska   34   -0.121
1     2009         All Determinants        Arizona   27   -0.037
2     2009         All Determinants       Arkansas   41   -0.264
3     2009         All Determinants     California   24    0.134
4     2009         All Determinants        Alabama   43   -0.306
...    ...                      ...            ...  ...      ...
2269  2019  Primary Care Physicians        Vermont   11  188.700
2270  2019  Primary Care Physicians     Washington   23  150.000
2271  2019  Primary Care Physicians      Wisconsin   21  152.400
2272  2019  Primary Care Physicians  West Virginia   14  172.800
2273  2019  Primary Care Physicians        Wyoming   46  111.000

[2274 rows x 5 columns]

In [15]:
cleanRankings.to_csv('../output_file/state_health_.csv',index=True)